import React from 'react'
import styles from '@/styles/404.module.css'
import Head from 'next/head'
import Link from 'next/link'

export default function Notfound() {
  return (
    <>
      <Head>
        <title>Not Found</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icons/svg/logo-no-background.svg" />
      </Head>
      <main className={styles.container}>
        <h1>Page Not Found - <Link href='/'>Let&apos;s go back to drink</Link></h1>
        <iframe src="https://giphy.com/embed/sEH3lMz5hMBEc" width="480" height="359" frameBorder="0" className="giphy-embed" allowFullScreen></iframe>
      </main>
    </>
  )
}
